TRUNCATE TABLE "profile" CASCADE;
INSERT INTO "profile" ("id","name","title","bio","avatar_url","theme_color","background_image_url","background_blur","card_opacity","bio_title","bio_title_color","bio_body","bio_body_color","bio_footer","bio_footer_color","bio_border_color","bio_background_color","font_family","border_radius","floating_emojis","kick_username","kick_autoplay","layout_config","announcement_text","announcement_enabled","announcement_color","cta_button_text","cta_button_url","cta_button_enabled","stats_enabled","stats_followers","stats_views","site_title","favicon_url","lol_summoner_name","lol_region","lol_widget_enabled","lol_widget_settings","lol_riot_tag","riot_api_key") VALUES ('c9b8e2f0-43c7-4481-bf53-a6ac5efadc5a','ThePublisher','Kick & YouTube İçerik Üreticisi','','','#e9301c','/uploads/1771547436398-8mfs0o07ecr.jpg',0,80,'Kick & YouTube İçerik Üreticisi','#ff0000','Merhaba! Ben bir içerik üreticisiyim. Kick''te canlı yayınlar yapıyor, YouTube''da gaming ve eğlence içerikleri üretiyorum. Topluluğumuzla birlikte eğlenceli vakit geçiriyoruz. Beni sosyal medyadan takip edebilir, sponsorlarımın sunduğu özel indirim kodlarından yararlanabilirsiniz!','#333333','','#ff0000','','#fffBEB','Nunito','2rem',false,'ThePublisher',true,'[{"id":"bio","width":"full","visible":true},{"id":"socials","width":"full","visible":true},{"id":"kick","width":"full","visible":true},{"id":"sponsors","width":"full","visible":true},{"id":"games","width":"full","visible":true},{"id":"lol","width":"full","visible":true},{"id":"contact","width":"full","visible":true}]','',false,'#7c3aed','','',false,false,'','','ThePublisher',' ','Seahlorm','EUW1',true,'{"showRank":true,"cardColor":"#000000","matchCount":5,"accentColor":"#a78bfa","showWinrate":true,"showLastMatches":true,"showTopChampions":false}','EUW',NULL);

TRUNCATE TABLE "social_links" CASCADE;
INSERT INTO "social_links" ("id","platform","url","follower_count","badge","description","display_order","is_active","col_span","custom_bg_color","custom_text_color","display_style") VALUES ('5d4771cc-5972-446d-866a-faf0eb95d93a','Kick','https://kick.com/gamemaster',NULL,NULL,NULL,1,true,2,NULL,NULL,'standard');
INSERT INTO "social_links" ("id","platform","url","follower_count","badge","description","display_order","is_active","col_span","custom_bg_color","custom_text_color","display_style") VALUES ('1dce3896-ad93-4f04-8a14-9190be87a9e4','YouTube','https://youtube.com/@gamemaster',NULL,NULL,NULL,2,true,2,NULL,NULL,'standard');
INSERT INTO "social_links" ("id","platform","url","follower_count","badge","description","display_order","is_active","col_span","custom_bg_color","custom_text_color","display_style") VALUES ('ca3332a1-c428-443f-a057-7a12b04ef32d','Instagram','https://instagram.com/gamemaster',NULL,NULL,NULL,5,true,2,NULL,NULL,'standard');
INSERT INTO "social_links" ("id","platform","url","follower_count","badge","description","display_order","is_active","col_span","custom_bg_color","custom_text_color","display_style") VALUES ('fdc89c7c-24dd-44f6-94f7-558472370a6d','Discord','https://discord.gg/gamemaster',NULL,NULL,NULL,3,true,2,NULL,NULL,'standard');
INSERT INTO "social_links" ("id","platform","url","follower_count","badge","description","display_order","is_active","col_span","custom_bg_color","custom_text_color","display_style") VALUES ('ac85e57f-1891-4406-b7cc-9908ea0519e7','Twitter','https://twitter.com/gamemaster',NULL,NULL,NULL,4,true,2,NULL,NULL,'icon');
INSERT INTO "social_links" ("id","platform","url","follower_count","badge","description","display_order","is_active","col_span","custom_bg_color","custom_text_color","display_style") VALUES ('cfe3842a-7940-4883-b8c4-2b0e204b9f5e','TikTok','https://tiktok.com/@gamemaster',NULL,NULL,NULL,6,true,2,NULL,NULL,'icon');

TRUNCATE TABLE "sponsors" CASCADE;
INSERT INTO "sponsors" ("id","name","description","logo_url","website_url","code","discount_percent","display_order","is_active","col_span","custom_bg_color","custom_text_color") VALUES ('dd0be7b8-169f-4d9d-8d7d-c613827a0950','TechGear Pro','Profesyonel gaming ekipmanları ve aksesuarlar. En yüksek performans için en iyi donanım.',NULL,'https://techgearpro.com',NULL,NULL,1,true,2,NULL,NULL);
INSERT INTO "sponsors" ("id","name","description","logo_url","website_url","code","discount_percent","display_order","is_active","col_span","custom_bg_color","custom_text_color") VALUES ('d9f2e354-ee10-44c5-a191-f98638d4a3b4','GamerFuel','Oyuncular için özel formüllü enerji içecekleri. Maratonluk oyun seansları için güç kaynağı.',NULL,'https://gamerfuel.com',NULL,NULL,2,true,2,NULL,NULL);
INSERT INTO "sponsors" ("id","name","description","logo_url","website_url","code","discount_percent","display_order","is_active","col_span","custom_bg_color","custom_text_color") VALUES ('fae43239-6bf6-4a1b-bd82-90912cc519a1','StreamPro Setup','Yayıncılar için profesyonel ekipman çözümleri. Işık, mikrofon ve kamera setleri.',NULL,'https://streamprosetup.com',NULL,NULL,3,true,2,NULL,NULL);

TRUNCATE TABLE "discount_codes" CASCADE;
INSERT INTO "discount_codes" ("id","sponsor_id","code","description","discount_percent","url","logo_url","display_order","is_active") VALUES ('73ffbeba-74c3-4f6a-963e-f4a995c2b034','dd0be7b8-169f-4d9d-8d7d-c613827a0950','GAMEMASTER15','TechGear Pro''da tüm ürünlerde geçerli',15,'https://techgearpro.com?ref=gamemaster',NULL,1,true);
INSERT INTO "discount_codes" ("id","sponsor_id","code","description","discount_percent","url","logo_url","display_order","is_active") VALUES ('1be8047e-bea1-44d9-9085-2267c9323f5d','d9f2e354-ee10-44c5-a191-f98638d4a3b4','FUEL20','GamerFuel enerji içeceklerinde özel indirim',20,'https://gamerfuel.com?ref=gamemaster',NULL,2,true);
INSERT INTO "discount_codes" ("id","sponsor_id","code","description","discount_percent","url","logo_url","display_order","is_active") VALUES ('d18ba1e5-fe4c-4f9c-8c23-cd8b9d23bec1','fae43239-6bf6-4a1b-bd82-90912cc519a1','STREAM25','StreamPro Setup''ta yayıncı paketlerinde geçerli',25,'https://streamprosetup.com?ref=gamemaster',NULL,3,true);

